### ISSUE TITLE
Request to add a Python package

### ISSUE THREAD

**Issue by hasibzunair** [s4kibs4mi/made-in-bangladesh#6]
A package to send email notifications along with attachments remotely. Can be added to any existing piece of python scripts with few lines of code. 

Link to package is [here](https://test.pypi.org/project/pynotify/) . Also the [github](https://github.com/hasibzunair/neuralert) repo, has **17 stars**  currently.

If it's useful, please let me know, will send a PR.

**Comment by s4kibs4mi** [comment]
@hasibzunair sure, please send PR. Thank you.

**Comment by s4kibs4mi** [comment]
@hasibzunair Added. Thanks.

**Comment by hasibzunair** [comment]
Yay! Thanks.
